### ISSUE TITLE
[Bug] joining node data synchronization  

### ISSUE THREAD

**Issue by ddeguglielmo** [eclipse-zenoh/zenoh-backend-filesystem#18]
### Describe the bug

We have the following scenario:
- 1 running zenohd peer (**zenohd-1**) with filesystem backend subscribed to key expression "/demo/example/**" having 2 keys stored in its storage directory: _key1)_ **path**: /demo/example/one **value**: one-2, _key2)_ **path**: /demo/example/two **value**: two-1
 
- 1 joining zenohd peer (**zenohd-2**) with filesystem backend subscribed to key expression "/demo/example/**" having 3 keys stored in its storage directory: _key1)_ **path**: /demo/example/one **value**: one-1, _key2)_ **path**: /demo/example/two **value**: two-2, _key3)_ **path**: /demo/example/three **value**: three

Please note that:
- the key1 value stored on zenohd-1 has a more recent timestamp with respect to the key1 value stored on zenohd-2
- the key2 value stored on zenohd-2 has a more recent timestamp with respect to the key2 value stored on zenohd-1
- key3 is only stored on zenohd-2

Some time after the joining of zenohd-2 we have the following situation:

**zenohd-1**

key1) path: /demo/example/one value: one-2
key2) path: /demo/example/two value: two-1

**zenohd-2**

key1) path: /demo/example/one value: one-2
key2) path: /demo/example/two value: two-2
key3) path: /demo/example/three value: three

You can note that zenohd-1 has not received key3 and that it continues to store value two-1 for key2 that is not the most recent value for key2. This is confirmed by the output of the following commands executed on node zenohd-1

```
curl http://localhost:8000/demo/example/**

[
{ "key": "/demo/example/one", "value": "one-2", "encoding": "text/plain", "time": "2022-05-20T09:37:54.696046967Z/62B969A094F94A7BB4E2D59F3484DC73" },
{ "key": "/demo/example/two", "value": "two-1", "encoding": "text/plain", "time": "2022-05-20T09:34:36.910040009Z/AA3CB3758F164904BA69CF80B6B3449B" }
]
```
and node zenohd-2

```
curl http://localhost:8000/demo/example/**
[
{ "key": "/demo/example/one", "value": "one-2", "encoding": "text/plain", "time": "2022-05-20T09:37:54.696046967Z/62B969A094F94A7BB4E2D59F3484DC73" },
{ "key": "/demo/example/two", "value": "two-2", "encoding": "text/plain", "time": "2022-05-20T09:36:18.603789389Z/2EB06EC59DDB4AE09570B3237C1DB3F7" },
{ "key": "/demo/example/three", "value": "three", "encoding": "text/plain", "time": "2022-05-20T09:36:52.199742238Z/2EB06EC59DDB4AE09570B3237C1DB3F7" }
]
```

Is this behaviour expected? Thanks in advance for your help.

 

### To reproduce

1. Start **zenohd-1** and be sure that **zenohd-2** is off
2. Execute command: _z_put -k /demo/example/two -v two-1_

3. Stop zenohd-1 and start zenohd-2
4. Execute commands: _z_put -k /demo/example/one -v one-1_, _z_put -k /demo/example/one -v two-2_, _z_put -k /demo/example/three -v three_
5. Stop zenohd-2 and start again zenohd-1
6. Execute command: _z_put -k /demo/example/one -v one-2_
7.  Start zenohd-2 again 

### System info

- Platform: Ubuntu 20.04
- zenoh-backend-filesystem commit: 9ce3251203bca8bbc43b32737512cc05ec5381fc
- zenoh commit: d4b00540cd0faa6ce585e11862cf9740ca226489

**Comment by JEnoch** [comment]
The scenario you describe is what we call **storages alignment** after a divergence:
The 1st storage received publications that the 2nd didn't received, and vice-versa. Then they need to align their views wrt. the latest publication on each key.

Zenoh doesn't support such alignment yet. But that's work in progress.
You can have a first glance on the solution we foresee in this presentation that @sreeja made recently:
https://rainbowfs.gitlabpages.inria.fr/final-workshop/#sreeja-nair-adlink--title-consistency-in-zenoh-an-edge-data-fabric

In current implementation of zenoh, only **startup alignment** is implemented. 
This assumes that the joining storage starts as empty. At startup, the storage just queries the other storages on its key expression (_/demo/example/**_ in your case), and stores all the replies before starting its own subscription and queryable.

**Comment by Mallets** [comment]
This feature is now available in zenoh. A description on how it works and how to use it is available here: https://zenoh.io/blog/2022-11-29-zenoh-alignment/. Let us know if that solves your problem.
