### ISSUE TITLE
[Bug] Cross-builds failing on ARMs with RocksDB 0.19.0

### ISSUE THREAD

**Issue by JEnoch** [eclipse-zenoh/zenoh-backend-filesystem#28]
### Describe the bug

Following bump of rocksdb from `0.18.0` to `0.19.0` all cross-builds for ARMs platforms are failing.

This is the same issue than eclipse-zenoh/zenoh-backend-rocksdb#22 

### To reproduce

Run release workflow

### System info

- Zenoh commit dce7fa660e

**Comment by JEnoch** [comment]
Waiting for the issue to be solved in a rust-rocksdb release, we rollback to version 0.18.0 (via #29)

**Comment by Mallets** [comment]
Closing since we are already bumped rocksdb dependency to 0.20.1.
